name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=2.2.0
  - pytest=8.0.0
  - scipy=1.12.0
  - pip=24.0
  - pip:
      - mlflow==2.10.2
      - wandb==0.16.3
